### PR TITLE
moved main_driver.cpp from exec/compressible_stag to src_compressible…

### PR DESCRIPTION
**Pull request by emercado9**
…_stag/

### CODE REVIEW

**Comment by ajnonaka** [comment]
Looks good as long as compressible_stag builds correctly after a 'make realclean'

**Comment by emercado9** [comment]
> Looks good as long as compressible_stag builds correctly after a 'make realclean'

Yes, I was able to build after 'make realclean' without error

**Comment by ajnonaka** [comment]
If this is the only change you want in this PR, you can merge it.  You can then continue to work on branch compressible_stag_mui and open another new PR.

**Comment by emercado9** [comment]
> If this is the only change you want in this PR, you can merge it. You can then continue to work on branch compressible_stag_mui and open another new PR.

sounds good. thanks!

**Pull request merged**
